Fixed MissingReferenceException
MissingReferenceException: The object of type 'UnityEngine.Rigidbody2D' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.

Error was in HiveAgent.cs and it should be fixed now